### ISSUE TITLE
parseParams only parses numbers

### ISSUE THREAD

**Issue by sambev** [lipsmack/router-rx#1]
I have routes like `/users/:username` where `username` is a string.

Since parseParams only parses numbers my param is undefined.:
https://github.com/lipsmack/router-rx/blob/master/src/index.js#L107

Is there a reason parseParams only parses numbers?

**Comment by gschambers** [comment]
Oh, nice catch. There's no good reason at all. I've only been working with number parameters, so just an oversight. I'll add some more test cases for this and release an update.

**Comment by gschambers** [comment]
v1.3.2 has now been released to fix this issue.
